gText_Birch_Welcome::
	.string "Hello, young one.\p"
	.string "Don't be alarmed, I am a friend.\p"
	.string "I know it's strange, me visiting\n"
	.string "you in this dream.\p"
	.string "But I can assure you that you will\n"
	.string "learn who I am soon enough.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "We humans have lived alongside\n"
	.string "Pokémon for thousands of years.\p"
	.string "Sometimes as friends, workmates,\n"
	.string "and sometimes, we band together\l"
	.string "and battle others like us.\p"
	.string "But despite our history, we don't\n"
	.string "know everything about Pokémon.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "New travels and new friendships\n"
	.string "allow us to continue to unravel\l" 
	.string "new and old Pokémon mysteries.\p"
	.string "That's where you come in.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Ah, yes, that's right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Of course.\p"
	.string "You're {PLAYER}{KUN} who lives in\n"
	.string "Elderoot Town.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of Pokémon where dreams,\l"
	.string "adventure, and friendships await.\p"
	.string "$"
