CoaltineTunnel_B1F_MapScripts::
	.byte 0


CoaltineTunnel_B1F_EventScript_Ball1::
# 6 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	lock
# 7 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	removeobject 1
# 8 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	giveitem ITEM_MOON_STONE
# 9 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	release
	return


CoaltineTunnel_B1F_EventScript_Ball2::
# 13 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	lock
# 14 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	removeobject 2
# 15 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	giveitem ITEM_THUNDER_STONE
# 16 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	release
	return


CoaltineTunnel_B1F_EventScript_Ball3::
# 20 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	lock
# 21 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	removeobject 3
# 22 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	giveitem ITEM_WATER_STONE
# 23 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	release
	return


CoaltineTunnel_B1F_EventScript_Ball4::
# 27 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	lock
# 28 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	removeobject 4
# 29 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	giveitem ITEM_DUSK_STONE
# 30 "data/maps/CoaltineTunnel_B1F/scripts.pory"
	release
	return

